# Generated by Django 4.0.3 on 2023-06-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
