# Generated by Django 4.0.3 on 2023-06-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNumber',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appointment.appointment')),
                ('appointment_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
