# Generated by Django 4.0.3 on 2023-06-21 13:17


from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='id',
            new_name='doctor_id',
        ),
    ]
